#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo ' Styling, testing and building your project before committing'

# Check Prettier
npm run check-format || 
{
    echo 'Prettier Check Failed. Run => npm run format, add changes and try to commit again';
    false;
}

# Check ESLint
npm run check-lint || 
{
    echo "ESLint Checking Failed. Make the required changes listed above, add changes and try to commit again";
    false;
}

# Check tsconfig
npm run check-types ||
{
    echo "Failed Type Check. Make the changes required above, add changes and try to commit again";
    false;
}

npm run build || 
{
    echo "Failed to Build, view the error above";
    false;
}

echo "Success Commit";